name: build-arm64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: build
        run: |
          cat <<EOF > Dockerfile
          FROM alpine:latest AS builder
          RUN apk add --no-cache gcc musl-dev make git
          COPY . /app
          WORKDIR /app
          # 暴力进入所有子目录尝试编译，直到找到 Makefile
          RUN cd /app && (cd src || cd .) && make

          FROM alpine:latest
          # 使用 find 命令把编译出来的文件找出来并移动到 bin
          COPY --from=builder /app /tmp/build
          RUN find /tmp/build -name rtp2httpd -exec cp {} /usr/bin/rtp2httpd \; && chmod +x /usr/bin/rtp2httpd
          ENTRYPOINT ["/usr/bin/rtp2httpd"]
          CMD ["-p", "5140"]
          EOF
          docker buildx build --platform linux/arm64 -t rtp2httpd:arm64 --output type=docker,dest=rtp2httpd_arm64.tar .

      - uses: actions/upload-artifact@v4
        with:
          name: rb5009-tar
          path: rtp2httpd_arm64.tar
