name: build-arm64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: build
        run: |
          cat <<EOF > Dockerfile
          FROM alpine:latest AS builder
          RUN apk add --no-cache gcc musl-dev make
          COPY . /src
          # 关键点：stackia 源码就在根目录的 src 下
          WORKDIR /src/src
          RUN make
          
          FROM alpine:latest
          # 编译产物就在当前 src 目录下
          COPY --from=builder /src/src/rtp2httpd /usr/bin/rtp2httpd
          RUN chmod +x /usr/bin/rtp2httpd
          ENTRYPOINT ["/usr/bin/rtp2httpd"]
          CMD ["-p", "5140"]
          EOF
          docker buildx build --platform linux/arm64 -t rtp2httpd:arm64 --output type=docker,dest=rtp2httpd_arm64.tar .
      - uses: actions/upload-artifact@v4
        with:
          name: rb5009-tar
          path: rtp2httpd_arm64.tar
